import * as esbuild from "esbuild"; // Changed to * as esbuild
import * as process from "process"; // Changed to * as process
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// process.argv is a string array
const prod = (process.argv[2] === "production");

// Explicitly type the context to satisfy the linter
async function runBuild() {
    const context = await esbuild.context({
        banner: {
            js: banner,
        },
        entryPoints: ["src/main.ts"],
        bundle: true,
        external: [
            "obsidian",
            "electron",
            "@codemirror/autocomplete",
            "@codemirror/collab",
            "@codemirror/commands",
            "@codemirror/language",
            "@codemirror/lint",
            "@codemirror/search",
            "@codemirror/state",
            "@codemirror/view",
            "@lezer/common",
            "@lezer/highlight",
            "@lezer/lr",
            ...builtinModules],
        format: "cjs",
        target: "es2018",
        logLevel: "info",
        sourcemap: prod ? false : "inline",
        treeShaking: true,
        outfile: "main.js",
        minify: prod,
    });

    if (prod) {
        await context.rebuild();
        process.exit(0);
    } else {
        await context.watch();
    }
}

// Execute the build function and catch errors
runBuild().catch(() => process.exit(1));